<a href="https://colab.research.google.com/github/JosenildoJunior/StatPyDataScience/blob/main/Popula%C3%A7%C3%A3o_e_Amostra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Estatística com Python: Um Guia para Estudos e Solução de Problemas

# *Carregando os dados*

Carregando a Base de Dados para Análise Estatística: Preparação para Estudos

In [6]:
# Acesso ao drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
# Manipulação de arquivos
import pandas as pd

# Biblioteca para funções randomicas
import random

# Funções matemáticas
import numpy as np

In [8]:
# Importando o dataset
df = pd.read_csv('/content/drive/MyDrive/Estatística para ciência de dados/census.csv')

In [9]:
# Observando os dados
df.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [10]:
# Observando as dimenções do dataset
df.shape

(32561, 15)

# **População** **e** **Amostra**

*Breve Resumo:* A população em estatística refere-se ao conjunto completo de elementos ou observações que estamos estudando. É importante definir claramente a população, pois isso afetará a validade de nossas conclusões estatísticas.

*Quando Utilizar:*
- Quando você deseja estudar e entender um grupo completo de elementos, como todos os habitantes de uma cidade, todos os clientes de uma loja, etc.
- Ao definir a base para seleção de uma amostra representativa.

*Breve Resumo:* Uma amostra é uma parte representativa de uma população maior. Ela é usada para fazer inferências sobre a população como um todo, evitando a necessidade de coletar dados de toda a população, o que pode ser impraticável.

*Quando Utilizar:*
- Quando é difícil ou impossível coletar dados de toda a população.
- Para economizar tempo e recursos na coleta de dados.
- Para realizar experimentos ou estudos de pesquisa.

## **Amostragem Aleatória Simples**

 *Breve Resumo:* A amostragem aleatória simples é um método de seleção de amostras em que cada elemento da população tem uma chance igual de ser selecionado. Isso garante que a amostra seja representativa da população.

  *Quando Utilizar:*
  - Quando você deseja evitar vieses na seleção da amostra.
  - Quando a população é homogênea e não há subgrupos distintos.

*Utilizando a função 'sample' e passando o parâmetro 'n = 100', é possível retirar aleatoriamente apenas 100 registros do dataframe principal.*

In [ ]:
# Criando um novo data frame e adicionando nele 100 amostras retiradas aleatoriamente do df principal
df_amostragem_aleatoria_simples = df.sample(n = 100)

In [ ]:
# Verificando quantos registros foram armazenados
df_amostragem_aleatoria_simples.shape

(100, 15)

In [ ]:
# Observando os registros
df_amostragem_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
2483,74,Self-emp-not-inc,92298,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,10,United-States,<=50K
6244,18,Private,84253,11th,7,Never-married,Other-service,Own-child,White,Female,0,0,24,United-States,<=50K
17784,35,Private,328466,9th,5,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Mexico,<=50K
7758,62,Private,290754,10th,6,Widowed,Handlers-cleaners,Not-in-family,White,Female,0,0,40,United-States,<=50K
3316,47,Local-gov,242552,Some-college,10,Never-married,Protective-serv,Not-in-family,Black,Male,0,0,40,United-States,<=50K

*Caso você queira obter o mesmo resultado, basta adicionar o argumento 'random_state' e fornecer um número. Dessa forma, os resultados da amostragem serão sempre os mesmos, independentemente de quantas vezes o código seja executado.*

In [ ]:
# Retirando 100 amostras
df_amostragem_aleatoria_simples = df.sample(n = 100, random_state = 20)

In [ ]:
# Observando os dados
df_amostragem_aleatoria_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
13376,34,Private,105493,Masters,14,Divorced,Prof-specialty,Unmarried,White,Female,0,0,40,United-States,<=50K
7676,40,Private,235786,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,44,United-States,>50K
32188,29,Private,153416,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,<=50K
30550,43,Self-emp-not-inc,118261,Masters,14,Divorced,Other-service,Unmarried,White,Female,0,0,30,United-States,<=50K
18873,27,Private,244402,Assoc-acdm,12,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,>50K

Agora vamos criar uma função para realizar amostragem simples sempre que necessário.

In [ ]:
# Criando a função
def amostragem_aleatoria_simples(df, amostra):
  return df.sample(n = amostra, random_state = 2)

Vamos criar um novo dataframe chamado 'data_simples' para armazenar o resultado da nossa função.

In [ ]:
# Executando a função
data_simples = amostragem_aleatoria_simples(df, 100)

In [ ]:
# Verificando quantos registros foram armazenados
data_simples.shape

(100, 15)

In [ ]:
# Observando os registros
data_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
16054,42,State-gov,160369,HS-grad,9,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,>50K
32382,44,Local-gov,150171,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
10749,39,Local-gov,256997,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
15377,39,Private,147548,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29660,29,Federal-gov,106179,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Female,0,1408,40,United-States,<=50K

## **Amostragem sistemática**

*Breve Resumo:* A amostragem sistemática é um método de seleção de amostras em que os elementos são escolhidos em intervalos regulares após a seleção aleatória do primeiro elemento. Isso pode ser útil quando a população tem uma ordem natural.

  *Quando Utilizar:*
  - Quando a população tem uma ordem ou sequência natural (por exemplo, uma lista ordenada por data de nascimento).
  - Quando se deseja uma amostra representativa sem a necessidade de selecionar cada elemento individualmente.

In [ ]:
def amostragem_sistematica(dataset, amostras):
    # Calcula o tamanho do intervalo entre as amostras
    intervalo = len(dataset) // amostras  # Divide o tamanho do dataset pelo número desejado de amostras

    # Gera um número aleatório para determinar o ponto de partida
    inicio = random.randint(0, intervalo)  # Escolhe aleatoriamente um ponto de partida dentro do intervalo

    # Cria uma lista de índices para as amostras sistemáticas
    indices = np.arange(inicio, len(dataset), step=intervalo)  # Cria uma lista de índices com base no ponto de partida e no intervalo

    # Seleciona as amostras do conjunto de dados original
    amostra_sistematica = dataset.iloc[indices]  # Seleciona as amostras com base nos índices gerados

    # Retorna a amostra sistemática selecionada
    return amostra_sistematica

Vamos criar um novo dataframe chamado 'df_amostra_sistematica' para armazenar o resultado da nossa função.

In [ ]:
# Chamando a função para criar a amostra sistemática
df_amostra_sistematica = amostragem_sistematica(df, 100)

# Verificando quantos registros foram armazenados
df_amostra_sistematica.shape

(100, 15)

In [ ]:
# Observando os registros
df_amostra_sistematica.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
132,38,Self-emp-not-inc,120985,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,4386,0,35,United-States,<=50K
457,38,Private,351299,Some-college,10,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,50,United-States,<=50K
782,40,Private,130760,Assoc-voc,11,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
1107,29,Private,131088,HS-grad,9,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,25,United-States,<=50K
1432,32,Private,180871,Assoc-voc,11,Divorced,Sales,Not-in-family,White,Male,0,0,50,United-States,>50K

## **Amostragem por grupo**

*Breve Resumo:*
A amostragem de grupos, também conhecida como amostragem por conglomerados, é uma técnica estatística em que a população é dividida em grupos ou conglomerados, e em seguida, alguns desses grupos são selecionados aleatoriamente para compor a amostra. Cada grupo selecionado é uma representação da população, e a coleta de dados pode ser realizada dentro de cada grupo, se necessário. Essa abordagem é útil quando se lida com uma população extensa e dispersa.

*Quando Utilizar:*
- Quando a população é extensa e a coleta de dados de todos os elementos individualmente é impraticável devido a limitações de recursos.
- Quando se quer economizar recursos, como tempo e dinheiro, na coleta de dados, selecionando grupos em vez de indivíduos.
- Quando a população possui uma estrutura de agrupamento natural, como cidades em um país, departamentos em uma empresa ou famílias em uma vizinhança.
- Quando se deseja realizar análises hierárquicas, observando a variação em múltiplos níveis (por exemplo, alunos em escolas em distritos em um estudo educacional).
- Para reduzir custos logísticos associados à coleta de dados, como deslocamento e supervisão.

Lembre-se de que é fundamental garantir que os grupos selecionados sejam representativos da população para obter resultados válidos e evitar vieses na seleção.

In [23]:
# Função para realizar amostragem de grupos em um DataFrame 'df' com 'grupos' especificados.

def amostragem_grupo(df, grupos):

  # Calcula o tamanho do intervalo necessário para dividir a população em 'grupos' iguais.
  intervalo = len(df) / grupos

  # Inicializa uma lista 'ids_grupos' para armazenar as identificações dos grupos.
  ids_grupos = []

  # Inicializa uma variável 'id_grupo' para rastrear o grupo atual e 'contagem' para rastrear elementos no grupo.
  id_grupo = 0
  contagem = 0

  # Itera sobre as linhas do DataFrame 'df'.
  for _ in df.iterrows():

    # Atribui a identificação do grupo atual à lista 'ids_grupos'.
    ids_grupos.append(id_grupo)

    # Atualiza a contagem de elementos no grupo.
    contagem += 1

    # Verifica se a contagem ultrapassou o tamanho do intervalo.
    if contagem > intervalo:

      # Reinicia a contagem e muda para o próximo grupo.
      contagem = 0
      id_grupo += 1

  # Adiciona uma coluna 'grupo' ao DataFrame 'df' para indicar a qual grupo cada elemento pertence.
  df['grupo'] = ids_grupos

  # Define uma semente (seed) para garantir que os resultados sejam replicáveis.
  random.seed(2)

  # Seleciona aleatoriamente um grupo entre os disponíveis.
  grupo_selecionado = random.randint(0, grupos)

  # Retorna um subconjunto do DataFrame 'df' contendo apenas os elementos do grupo selecionado.
  return df[df['grupo'] == grupo_selecionado]

In [24]:
# Armazenando os valores na variável
df_amostragem_grupo = amostragem_grupo(df, 325)

# Observando quantos dados foram selecionados
df_amostragem_grupo.shape

(101, 16)

In [25]:
# Observando o id e quantos dados foram selecionados!
df_amostragem_grupo['grupo'].value_counts()

28    101
Name: grupo, dtype: int64

In [26]:
# Observando os registros
df_amostragem_grupo.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,grupo
2828,54,Self-emp-not-inc,175804,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K,28
2829,36,Private,107302,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K,28
2830,63,Local-gov,41161,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,55,United-States,<=50K,28
2831,39,Private,401832,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,48,United-States,<=50K,28
2832,57,Self-emp-not-inc,353808,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,60,United-States,>50K,28